version: '3.5'

services:
  nginx:
    image: nginx:1.17
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - nginx_www:/var/www
      - ${PUBLIC_DIR:-/var/togovar/public}:/var/www/public
      - app_sockets:/tmp/sockets
    ports:
      - ${NGINX_PORT:-80}:80
    logging: &logging
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    depends_on:
      - app
      - sparqlist
      - virtuoso
      - jbrowse
      - elasticsearch01
      - elasticsearch02
      - elasticsearch03
      - elasticsearch04
      - elasticsearch05

  app:
    build: docker/ruby
    image: togovar_app:${VERSION:-2021.1}
    env_file: togovar.env
    volumes:
      - ./app:/app
      - ./stanza:/usr/local/stanza
      - nginx_www:/var/www
      - ${PUBLIC_DIR:-/var/togovar/public}:/var/www/public
      - app_bundle:/usr/local/bundle
      - app_log:/app/log
      - app_node_modules:/app/node_modules
      - app_tmp:/app/tmp
      - app_sockets:/app/tmp/sockets
    logging:
      <<: *logging

  stanza:
    build: docker/stanza
    image: togovar_stanza:${VERSION:-2021.1}
    env_file: togovar.env
    volumes:
      - ./stanza:/stanza
    logging:
      <<: *logging

  jbrowse:
    build: docker/jbrowse
    image: togovar_jbrowse:${VERSION:-2021.1}
    env_file: togovar.env
    volumes:
      - ./docker/jbrowse/template/jbrowse_conf.json:/var/www/jbrowse_conf.json:ro
      - ${JBROWSE_VOLUMES_DATA:-/var/togovar/jbrowse}:/var/www/data
    logging:
      <<: *logging

  sparqlist:
    image: ghcr.io/dbcls/sparqlist:snapshot-67162ef
    env_file: togovar.env
    volumes:
      - ./sparqlist:/app/repository
    logging:
      <<: *logging

  virtuoso:
    image: openlink/virtuoso-opensource-7:7.2
    env_file: togovar.env
    volumes:
      - ${VIRTUOSO_VOLUMES_LOAD:-./data/virtuoso/load}:/load
      - ${VIRTUOSO_VOLUMES_DATABASE:-./data/virtuoso/database}:/database
      - ${VIRTUOSO_VOLUMES_SETTINGS:-./data/virtuoso/settings}:/settings
    logging:
      <<: *logging

  elasticsearch01: &es
    image: elasticsearch:7.16.3
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment: &es_env
      cluster.name: togovar-cluster
      node.name: node01
      cluster.initial_master_nodes: node01,node02,node03,node04,node05
      cluster.routing.allocation.disk.threshold_enabled: "false"
      discovery.seed_hosts: elasticsearch02,elasticsearch03,elasticsearch04,elasticsearch05
      ES_JAVA_OPTS: -Xms8g -Xmx8g
      bootstrap.memory_lock: "true"
      path.repo: /usr/share/elasticsearch/snapshot
    volumes:
      - ${ELASTICSEARCH_VOLUMES_01_DATA:-./data/elasticsearch/01/data}:/usr/share/elasticsearch/data
      - ${ELASTICSEARCH_VOLUMES_SNAPSHOT:-./data/elasticsearch/snapshot}:/usr/share/elasticsearch/snapshot
    logging:
      <<: *logging

  elasticsearch02:
    <<: *es
    environment:
      <<: *es_env
      node.name: node02
      discovery.seed_hosts: elasticsearch01,elasticsearch03,elasticsearch04,elasticsearch05
    volumes:
      - ${ELASTICSEARCH_VOLUMES_02_DATA:-./data/elasticsearch/02/data}:/usr/share/elasticsearch/data
      - ${ELASTICSEARCH_VOLUMES_SNAPSHOT:-./data/elasticsearch/snapshot}:/usr/share/elasticsearch/snapshot
    ports: []

  elasticsearch03:
    <<: *es
    environment:
      <<: *es_env
      node.name: node03
      discovery.seed_hosts: elasticsearch01,elasticsearch02,elasticsearch04,elasticsearch05
    volumes:
      - ${ELASTICSEARCH_VOLUMES_03_DATA:-./data/elasticsearch/03/data}:/usr/share/elasticsearch/data
      - ${ELASTICSEARCH_VOLUMES_SNAPSHOT:-./data/elasticsearch/snapshot}:/usr/share/elasticsearch/snapshot
    ports: []

  elasticsearch04:
    <<: *es
    environment:
      <<: *es_env
      node.name: node04
      discovery.seed_hosts: elasticsearch01,elasticsearch02,elasticsearch03,elasticsearch05
    volumes:
      - ${ELASTICSEARCH_VOLUMES_04_DATA:-./data/elasticsearch/04/data}:/usr/share/elasticsearch/data
      - ${ELASTICSEARCH_VOLUMES_SNAPSHOT:-./data/elasticsearch/snapshot}:/usr/share/elasticsearch/snapshot
    ports: []

  elasticsearch05:
    <<: *es
    environment:
      <<: *es_env
      node.name: node05
      discovery.seed_hosts: elasticsearch01,elasticsearch02,elasticsearch03,elasticsearch04
    volumes:
      - ${ELASTICSEARCH_VOLUMES_05_DATA:-./data/elasticsearch/05/data}:/usr/share/elasticsearch/data
      - ${ELASTICSEARCH_VOLUMES_SNAPSHOT:-./data/elasticsearch/snapshot}:/usr/share/elasticsearch/snapshot
    ports: []

volumes:
  nginx_www:
    name: togovar_nginx_www_${VERSION:-2021.1}
    driver: local
  app_bundle:
    name: togovar_app_bundle_${VERSION:-2021.1}
    driver: local
  app_log:
    name: togovar_app_log_${VERSION:-2021.1}
    driver: local
  app_node_modules:
    name: togovar_app_node_modules_${VERSION:-2021.1}
    driver: local
  app_tmp:
    name: togovar_app_tmp_${VERSION:-2021.1}
    driver: local
  app_sockets:
    name: togovar_app_sockets_${VERSION:-2021.1}
    driver: local
